2024-03-28 09:35:41,975 INFO    StreamThr :22212 [internal.py:wandb_internal():86] W&B internal server running at pid: 22212, started at: 2024-03-28 09:35:41.970767
2024-03-28 09:35:41,978 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:35:41,996 INFO    WriterThread:22212 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\run-5x9cvlu3.wandb
2024-03-28 09:35:42,004 DEBUG   SenderThread:22212 [sender.py:send():378] send: header
2024-03-28 09:35:42,004 DEBUG   SenderThread:22212 [sender.py:send():378] send: run
2024-03-28 09:35:43,300 INFO    SenderThread:22212 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files
2024-03-28 09:35:43,300 INFO    SenderThread:22212 [sender.py:_start_run_threads():1099] run started: 5x9cvlu3 with start time 1711598741.975386
2024-03-28 09:35:43,373 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:35:43,373 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:35:44,140 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:35:45,000 DEBUG   HandlerThread:22212 [system_info.py:__init__():26] System info init
2024-03-28 09:35:45,000 DEBUG   HandlerThread:22212 [system_info.py:__init__():41] System info init done
2024-03-28 09:35:45,000 INFO    HandlerThread:22212 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:35:45,000 INFO    SystemMonitor:22212 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:35:45,000 INFO    HandlerThread:22212 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:35:45,013 INFO    SystemMonitor:22212 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:35:45,013 INFO    SystemMonitor:22212 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:35:45,013 INFO    SystemMonitor:22212 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:22212 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:35:45,044 INFO    SystemMonitor:22212 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:35:45,044 DEBUG   HandlerThread:22212 [system_info.py:probe():150] Probing system
2024-03-28 09:35:45,059 DEBUG   HandlerThread:22212 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:35:45,059 DEBUG   HandlerThread:22212 [system_info.py:probe():198] Probing system done
2024-03-28 09:35:45,059 DEBUG   HandlerThread:22212 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:05:45.044290', 'startedAt': '2024-03-28T04:05:41.905349', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\CIFAR\\client2.py', 'codePathLocal': 'client2.py', 'codePath': 'client2.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.3616485595703}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:35:45,059 INFO    HandlerThread:22212 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:35:45,059 INFO    HandlerThread:22212 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:35:45,059 DEBUG   HandlerThread:22212 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:35:45,059 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:35:45,328 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\conda-environment.yaml
2024-03-28 09:35:47,751 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:47,752 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,703 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,708 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:13,302 DEBUG   HandlerThread:22212 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:36:13,302 INFO    HandlerThread:22212 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:36:13,333 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,333 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,333 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,333 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,333 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,343 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,343 DEBUG   SenderThread:22212 [sender.py:send():378] send: files
2024-03-28 09:36:13,343 INFO    SenderThread:22212 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:36:13,517 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\conda-environment.yaml
2024-03-28 09:36:13,517 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\wandb-metadata.json
2024-03-28 09:36:14,256 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,256 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,492 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:36:14,492 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:36:14,492 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:14,492 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:14,492 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:14,524 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\requirements.txt
2024-03-28 09:36:14,644 INFO    wandb-upload_0:22212 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmphx7o5j2qwandb\8rk789ai-wandb-metadata.json
2024-03-28 09:36:14,914 DEBUG   SenderThread:22212 [sender.py:send():378] send: telemetry
2024-03-28 09:36:16,897 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:16,897 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:17,951 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:19,556 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:19,556 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,998 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:24,930 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:24,930 ERROR   gpu       :22212 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:28,041 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:29,609 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:29,614 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:29,615 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:33,542 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:35,027 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\output.log
2024-03-28 09:36:37,045 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\output.log
2024-03-28 09:36:39,150 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:44,243 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:44,565 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:44,628 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:44,644 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:45,062 DEBUG   SystemMonitor:22212 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 09:36:45,109 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\config.yaml
2024-03-28 09:36:45,140 DEBUG   SenderThread:22212 [sender.py:send():378] send: stats
2024-03-28 09:36:50,175 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:55,210 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:59,590 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:59,590 DEBUG   SenderThread:22212 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:59,637 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:37:00,422 DEBUG   HandlerThread:22212 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:01,234 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\output.log
2024-03-28 09:37:03,253 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\output.log
2024-03-28 09:37:03,830 INFO    cpu       :22212 [interfaces.py:monitor():140] Process cpu has exited.
2024-03-28 09:37:03,832 DEBUG   SystemMonitor:22212 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:37:03,832 DEBUG   SystemMonitor:22212 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:37:03,834 DEBUG   SenderThread:22212 [sender.py:send():378] send: stats
2024-03-28 09:37:05,314 INFO    MainThread:22212 [internal.py:handle_exit():76] Internal process exited
2024-03-28 09:37:05,314 INFO    Thread-16 :22212 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-5x9cvlu3\files\output.log
