2024-03-28 09:53:44,225 INFO    StreamThr :16160 [internal.py:wandb_internal():86] W&B internal server running at pid: 16160, started at: 2024-03-28 09:53:44.222621
2024-03-28 09:53:44,227 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:53:44,244 INFO    WriterThread:16160 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\run-a2j5pmex.wandb
2024-03-28 09:53:44,246 DEBUG   SenderThread:16160 [sender.py:send():378] send: header
2024-03-28 09:53:44,247 DEBUG   SenderThread:16160 [sender.py:send():378] send: run
2024-03-28 09:53:45,234 INFO    SenderThread:16160 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files
2024-03-28 09:53:45,234 INFO    SenderThread:16160 [sender.py:_start_run_threads():1099] run started: a2j5pmex with start time 1711599824.227151
2024-03-28 09:53:45,248 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:53:45,248 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:53:45,727 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:53:45,784 DEBUG   HandlerThread:16160 [system_info.py:__init__():26] System info init
2024-03-28 09:53:45,784 DEBUG   HandlerThread:16160 [system_info.py:__init__():41] System info init done
2024-03-28 09:53:45,784 INFO    HandlerThread:16160 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:53:45,785 INFO    SystemMonitor:16160 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:53:45,785 INFO    HandlerThread:16160 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:53:45,790 INFO    SystemMonitor:16160 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:53:45,791 INFO    SystemMonitor:16160 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:53:45,792 INFO    SystemMonitor:16160 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:53:45,794 INFO    SystemMonitor:16160 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:53:45,805 INFO    SystemMonitor:16160 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:53:45,816 DEBUG   HandlerThread:16160 [system_info.py:probe():150] Probing system
2024-03-28 09:53:45,818 DEBUG   HandlerThread:16160 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:53:45,818 DEBUG   HandlerThread:16160 [system_info.py:probe():198] Probing system done
2024-03-28 09:53:45,819 DEBUG   HandlerThread:16160 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:23:45.816702', 'startedAt': '2024-03-28T04:23:44.203058', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.1134948730469}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:53:45,819 INFO    HandlerThread:16160 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:53:45,819 INFO    HandlerThread:16160 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:53:45,819 DEBUG   HandlerThread:16160 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:53:45,824 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:46,247 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\conda-environment.yaml
2024-03-28 09:53:47,836 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:49,869 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:51,887 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:53,917 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:55,929 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:57,955 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:53:59,972 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:02,009 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:04,039 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:06,065 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:07,441 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\conda-environment.yaml
2024-03-28 09:54:07,562 DEBUG   HandlerThread:16160 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:54:07,564 INFO    HandlerThread:16160 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:07,582 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:07,584 DEBUG   SenderThread:16160 [sender.py:send():378] send: files
2024-03-28 09:54:07,584 INFO    SenderThread:16160 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:54:08,092 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:08,454 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\wandb-metadata.json
2024-03-28 09:54:08,632 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:54:08,633 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:54:08,633 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:08,634 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:08,634 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:09,464 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\requirements.txt
2024-03-28 09:54:10,112 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:11,262 DEBUG   SenderThread:16160 [sender.py:send():378] send: telemetry
2024-03-28 09:54:11,262 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:11,481 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\output.log
2024-03-28 09:54:12,125 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:12,621 INFO    wandb-upload_0:16160 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmppr_mnjjnwandb\ok97moeq-wandb-metadata.json
2024-03-28 09:54:13,505 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\output.log
2024-03-28 09:54:14,151 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:16,215 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:16,299 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:18,244 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:18,560 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\config.yaml
2024-03-28 09:54:20,262 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:22,282 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:22,644 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:23,629 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:23,629 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:23,630 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:24,310 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:26,330 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:28,202 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:28,354 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:30,375 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:32,401 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:33,254 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:34,418 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:35,716 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\output.log
2024-03-28 09:54:36,439 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:38,407 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:38,454 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:38,628 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:38,629 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:38,643 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:40,479 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:42,496 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:44,067 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:44,511 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:45,819 DEBUG   SystemMonitor:16160 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 09:54:45,820 DEBUG   SenderThread:16160 [sender.py:send():378] send: stats
2024-03-28 09:54:46,597 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:48,612 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:49,858 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:50,663 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:52,678 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:53,629 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:53,630 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:53,660 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:54,703 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:54,975 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:56,722 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:58,744 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:00,025 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:00,765 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:02,775 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:04,787 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:05,088 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:06,799 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:08,637 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:55:08,637 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:55:08,670 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:55:08,818 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:10,844 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:11,038 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:12,862 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:14,888 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:15,829 DEBUG   SenderThread:16160 [sender.py:send():378] send: stats
2024-03-28 09:55:16,840 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:16,953 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:18,989 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:21,004 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:21,884 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:23,024 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:23,647 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:55:23,647 DEBUG   SenderThread:16160 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:55:23,679 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:55:25,044 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:27,068 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:27,387 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:28,191 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\output.log
2024-03-28 09:55:29,109 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:31,149 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:32,407 DEBUG   HandlerThread:16160 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:33,250 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:35,269 ERROR   gpu       :16160 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:36,181 INFO    memory    :16160 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 09:55:36,183 DEBUG   SystemMonitor:16160 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:55:36,183 DEBUG   SystemMonitor:16160 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:55:36,185 DEBUG   SenderThread:16160 [sender.py:send():378] send: stats
2024-03-28 09:55:36,258 INFO    Thread-16 :16160 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095344-a2j5pmex\files\output.log
2024-03-28 09:55:37,694 INFO    MainThread:16160 [internal.py:handle_exit():76] Internal process exited
