2024-03-28 09:35:42,028 INFO    StreamThr :14636 [internal.py:wandb_internal():86] W&B internal server running at pid: 14636, started at: 2024-03-28 09:35:42.028702
2024-03-28 09:35:42,044 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:35:42,059 INFO    WriterThread:14636 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\run-udx4dwhb.wandb
2024-03-28 09:35:42,064 DEBUG   SenderThread:14636 [sender.py:send():378] send: header
2024-03-28 09:35:42,066 DEBUG   SenderThread:14636 [sender.py:send():378] send: run
2024-03-28 09:35:43,318 INFO    SenderThread:14636 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files
2024-03-28 09:35:43,318 INFO    SenderThread:14636 [sender.py:_start_run_threads():1099] run started: udx4dwhb with start time 1711598742.028701
2024-03-28 09:35:43,382 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:35:43,382 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:35:44,124 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:35:45,013 DEBUG   HandlerThread:14636 [system_info.py:__init__():26] System info init
2024-03-28 09:35:45,013 DEBUG   HandlerThread:14636 [system_info.py:__init__():41] System info init done
2024-03-28 09:35:45,013 INFO    HandlerThread:14636 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:35:45,013 INFO    SystemMonitor:14636 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:35:45,013 INFO    HandlerThread:14636 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:35:45,028 INFO    SystemMonitor:14636 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:14636 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:14636 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:14636 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:35:45,044 INFO    SystemMonitor:14636 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:35:45,076 DEBUG   HandlerThread:14636 [system_info.py:probe():150] Probing system
2024-03-28 09:35:45,076 DEBUG   HandlerThread:14636 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:35:45,076 DEBUG   HandlerThread:14636 [system_info.py:probe():198] Probing system done
2024-03-28 09:35:45,076 DEBUG   HandlerThread:14636 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:05:45.076610', 'startedAt': '2024-03-28T04:05:42.013030', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\CIFAR\\client1.py', 'codePathLocal': 'client1.py', 'codePath': 'client1.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.3616485595703}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:35:45,076 INFO    HandlerThread:14636 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:35:45,076 INFO    HandlerThread:14636 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:35:45,076 DEBUG   HandlerThread:14636 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:35:45,089 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:35:45,340 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\conda-environment.yaml
2024-03-28 09:35:47,750 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:47,751 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,703 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,703 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:13,098 DEBUG   HandlerThread:14636 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:36:13,098 INFO    HandlerThread:14636 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:13,129 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:13,129 DEBUG   SenderThread:14636 [sender.py:send():378] send: files
2024-03-28 09:36:13,129 INFO    SenderThread:14636 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:36:13,533 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\conda-environment.yaml
2024-03-28 09:36:13,533 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\wandb-metadata.json
2024-03-28 09:36:14,256 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,256 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,350 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:36:14,350 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:36:14,350 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:14,350 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:14,350 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:14,507 INFO    wandb-upload_0:14636 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpwkiucdv2wandb\87xtm55h-wandb-metadata.json
2024-03-28 09:36:14,538 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\requirements.txt
2024-03-28 09:36:14,759 DEBUG   SenderThread:14636 [sender.py:send():378] send: telemetry
2024-03-28 09:36:16,897 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:16,897 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:17,770 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:19,556 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:19,556 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,809 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:24,930 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:24,930 ERROR   gpu       :14636 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:27,850 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:29,458 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:29,521 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:29,569 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:33,078 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:36,094 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:36:38,114 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:36:38,568 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:43,590 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:44,233 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\config.yaml
2024-03-28 09:36:44,486 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:44,486 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:44,486 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:45,062 DEBUG   SystemMonitor:14636 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 09:36:45,062 DEBUG   SenderThread:14636 [sender.py:send():378] send: stats
2024-03-28 09:36:49,091 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:54,125 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:59,202 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:59,498 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:59,498 DEBUG   SenderThread:14636 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:59,498 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:37:01,470 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:03,533 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:04,394 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:05,577 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:07,625 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:09,526 DEBUG   HandlerThread:14636 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:09,655 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:11,669 INFO    memory    :14636 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 09:37:11,670 DEBUG   SystemMonitor:14636 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:37:11,670 DEBUG   SystemMonitor:14636 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:37:11,672 DEBUG   SenderThread:14636 [sender.py:send():378] send: stats
2024-03-28 09:37:11,673 INFO    Thread-16 :14636 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\files\output.log
2024-03-28 09:37:12,006 WARNING StreamThr :14636 [internal.py:is_dead():414] Internal process exiting, parent pid 9632 disappeared
2024-03-28 09:37:12,006 ERROR   StreamThr :14636 [internal.py:wandb_internal():152] Internal process shutdown.
2024-03-28 09:37:12,671 INFO    HandlerThread:14636 [handler.py:finish():869] shutting down handler
2024-03-28 09:37:12,672 INFO    HandlerThread:14636 [system_monitor.py:finish():203] Stopping system monitor
2024-03-28 09:37:12,672 INFO    HandlerThread:14636 [interfaces.py:finish():202] Joined cpu monitor
2024-03-28 09:37:12,673 INFO    HandlerThread:14636 [interfaces.py:finish():202] Joined disk monitor
2024-03-28 09:37:12,679 INFO    SenderThread:14636 [sender.py:finish():1521] shutting down sender
2024-03-28 09:37:12,679 INFO    WriterThread:14636 [datastore.py:close():296] close: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093542-udx4dwhb\run-udx4dwhb.wandb
2024-03-28 09:37:13,025 INFO    MainThread:14636 [internal.py:handle_exit():76] Internal process exited
