2024-03-28 09:35:41,956 INFO    StreamThr :1588 [internal.py:wandb_internal():86] W&B internal server running at pid: 1588, started at: 2024-03-28 09:35:41.948140
2024-03-28 09:35:41,960 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:35:41,978 INFO    WriterThread:1588 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\run-2advj6vv.wandb
2024-03-28 09:35:41,981 DEBUG   SenderThread:1588 [sender.py:send():378] send: header
2024-03-28 09:35:41,982 DEBUG   SenderThread:1588 [sender.py:send():378] send: run
2024-03-28 09:35:43,318 INFO    SenderThread:1588 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files
2024-03-28 09:35:43,318 INFO    SenderThread:1588 [sender.py:_start_run_threads():1099] run started: 2advj6vv with start time 1711598741.960404
2024-03-28 09:35:43,382 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:35:43,382 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:35:44,171 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:35:45,013 DEBUG   HandlerThread:1588 [system_info.py:__init__():26] System info init
2024-03-28 09:35:45,013 DEBUG   HandlerThread:1588 [system_info.py:__init__():41] System info init done
2024-03-28 09:35:45,013 INFO    HandlerThread:1588 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:35:45,013 INFO    SystemMonitor:1588 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:35:45,013 INFO    HandlerThread:1588 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:35:45,028 INFO    SystemMonitor:1588 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:1588 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:1588 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:35:45,028 INFO    SystemMonitor:1588 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:35:45,044 INFO    SystemMonitor:1588 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:35:45,076 DEBUG   HandlerThread:1588 [system_info.py:probe():150] Probing system
2024-03-28 09:35:45,076 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:35:45,076 DEBUG   HandlerThread:1588 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:35:45,076 DEBUG   HandlerThread:1588 [system_info.py:probe():198] Probing system done
2024-03-28 09:35:45,076 DEBUG   HandlerThread:1588 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:05:45.076610', 'startedAt': '2024-03-28T04:05:41.905349', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\CIFAR\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.3616485595703}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:35:45,076 INFO    HandlerThread:1588 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:35:45,076 INFO    HandlerThread:1588 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:35:45,076 DEBUG   HandlerThread:1588 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:35:45,340 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\conda-environment.yaml
2024-03-28 09:35:47,751 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:47,751 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:50,406 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:53,048 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,708 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:55,708 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:58,352 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:00,997 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:03,661 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:06,311 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:08,974 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:11,623 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:12,528 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\conda-environment.yaml
2024-03-28 09:36:12,544 DEBUG   HandlerThread:1588 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:36:12,567 INFO    HandlerThread:1588 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:36:12,590 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:12,590 DEBUG   SenderThread:1588 [sender.py:send():378] send: files
2024-03-28 09:36:12,590 INFO    SenderThread:1588 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:36:13,533 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\wandb-metadata.json
2024-03-28 09:36:13,959 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:36:13,974 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:36:13,974 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:13,974 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:13,974 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:13,990 INFO    wandb-upload_0:1588 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpwy8393pawandb\iabkf6kn-wandb-metadata.json
2024-03-28 09:36:14,256 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,256 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:14,397 DEBUG   SenderThread:1588 [sender.py:send():378] send: telemetry
2024-03-28 09:36:14,538 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\requirements.txt
2024-03-28 09:36:14,540 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\output.log
2024-03-28 09:36:16,543 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\output.log
2024-03-28 09:36:16,897 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:16,897 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:18,437 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:19,556 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:19,556 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:22,204 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:23,474 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:24,930 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:24,930 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:36:28,511 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:29,134 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:29,134 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:29,134 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:29,755 ERROR   gpu       :1588 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:36:33,652 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:37,107 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\output.log
2024-03-28 09:36:38,953 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:43,991 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:44,006 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:44,148 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:36:44,407 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:45,062 DEBUG   SystemMonitor:1588 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 09:36:45,062 DEBUG   SenderThread:1588 [sender.py:send():378] send: stats
2024-03-28 09:36:45,250 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\config.yaml
2024-03-28 09:36:50,096 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:55,131 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:36:58,984 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:36:58,984 DEBUG   SenderThread:1588 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:36:59,162 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:37:00,487 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:05,530 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:10,712 INFO    Thread-16 :1588 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_093541-2advj6vv\files\output.log
2024-03-28 09:37:11,136 DEBUG   HandlerThread:1588 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:37:13,697 INFO    memory    :1588 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 09:37:13,697 DEBUG   SystemMonitor:1588 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:37:13,697 DEBUG   SystemMonitor:1588 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:37:13,697 DEBUG   SenderThread:1588 [sender.py:send():378] send: stats
2024-03-28 09:37:15,035 INFO    MainThread:1588 [internal.py:handle_exit():76] Internal process exited
