2024-03-28 00:15:53,306 INFO    StreamThr :1264 [internal.py:wandb_internal():86] W&B internal server running at pid: 1264, started at: 2024-03-28 00:15:53.306897
2024-03-28 00:15:53,322 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status
2024-03-28 00:15:53,370 INFO    WriterThread:1264 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\run-k4ppw99v.wandb
2024-03-28 00:15:53,370 DEBUG   SenderThread:1264 [sender.py:send():378] send: header
2024-03-28 00:15:53,385 DEBUG   SenderThread:1264 [sender.py:send():378] send: run
2024-03-28 00:15:54,652 INFO    SenderThread:1264 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files
2024-03-28 00:15:54,652 INFO    SenderThread:1264 [sender.py:_start_run_threads():1099] run started: k4ppw99v with start time 1711565153.322578
2024-03-28 00:15:54,667 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 00:15:54,667 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: check_version
2024-03-28 00:15:55,172 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 00:15:55,951 DEBUG   HandlerThread:1264 [system_info.py:__init__():26] System info init
2024-03-28 00:15:55,951 DEBUG   HandlerThread:1264 [system_info.py:__init__():41] System info init done
2024-03-28 00:15:55,951 INFO    HandlerThread:1264 [system_monitor.py:start():194] Starting system monitor
2024-03-28 00:15:55,951 INFO    SystemMonitor:1264 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 00:15:55,951 INFO    HandlerThread:1264 [system_monitor.py:probe():214] Collecting system info
2024-03-28 00:15:55,966 INFO    SystemMonitor:1264 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 00:15:55,966 INFO    SystemMonitor:1264 [interfaces.py:start():190] Started disk monitoring
2024-03-28 00:15:55,966 INFO    SystemMonitor:1264 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 00:15:55,966 INFO    SystemMonitor:1264 [interfaces.py:start():190] Started memory monitoring
2024-03-28 00:15:55,966 INFO    SystemMonitor:1264 [interfaces.py:start():190] Started network monitoring
2024-03-28 00:15:55,982 DEBUG   HandlerThread:1264 [system_info.py:probe():150] Probing system
2024-03-28 00:15:55,982 DEBUG   HandlerThread:1264 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 00:15:55,982 DEBUG   HandlerThread:1264 [system_info.py:probe():198] Probing system done
2024-03-28 00:15:55,982 DEBUG   HandlerThread:1264 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-27T18:45:55.982468', 'startedAt': '2024-03-27T18:45:53.236715', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\CIFAR\\client1.py', 'codePathLocal': 'client1.py', 'codePath': 'client1.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.3466453552246}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 00:15:55,982 INFO    HandlerThread:1264 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 00:15:55,982 INFO    HandlerThread:1264 [system_monitor.py:probe():227] Publishing system info
2024-03-28 00:15:55,982 DEBUG   HandlerThread:1264 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 00:15:55,982 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:15:56,668 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\conda-environment.yaml
2024-03-28 00:15:58,613 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:58,613 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:01,248 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:01,248 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:03,861 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:03,861 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:06,482 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:06,482 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:09,101 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:09,101 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:10,515 DEBUG   HandlerThread:1264 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 00:16:10,515 INFO    HandlerThread:1264 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:10,530 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:16:10,530 DEBUG   SenderThread:1264 [sender.py:send():378] send: files
2024-03-28 00:16:10,530 INFO    SenderThread:1264 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 00:16:10,784 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\conda-environment.yaml
2024-03-28 00:16:10,784 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\wandb-metadata.json
2024-03-28 00:16:11,223 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 00:16:11,239 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: python_packages
2024-03-28 00:16:11,240 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:11,240 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:11,240 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:11,734 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:11,760 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:11,790 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\requirements.txt
2024-03-28 00:16:11,869 DEBUG   SenderThread:1264 [sender.py:send():378] send: telemetry
2024-03-28 00:16:12,816 INFO    wandb-upload_0:1264 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmp2_3o5a1gwandb\axmowdqh-wandb-metadata.json
2024-03-28 00:16:14,399 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:14,414 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:14,894 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:16,819 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:16:17,039 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:17,039 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:18,833 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:16:19,703 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:19,704 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:20,397 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:22,351 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:22,351 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:24,996 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:24,996 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:25,428 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:25,894 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\config.yaml
2024-03-28 00:16:26,252 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:26,252 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:26,252 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:27,640 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:27,640 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:30,246 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:30,246 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:30,946 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:32,892 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:32,892 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:35,537 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:35,537 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:35,984 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:38,147 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:38,148 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:40,796 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:40,796 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:41,011 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:41,268 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:41,268 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:41,268 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:43,031 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:43,031 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:45,656 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:45,656 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:46,758 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:48,266 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:48,266 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:50,879 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:50,894 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:51,815 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:53,513 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:53,513 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:55,985 DEBUG   SystemMonitor:1264 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 00:16:55,985 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:16:56,126 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:56,126 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:56,282 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:56,282 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:56,283 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:57,808 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:58,768 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:58,768 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:01,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:01,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:02,842 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:04,007 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:04,007 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:06,683 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:06,684 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:07,888 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:09,364 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:09,364 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:11,294 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:11,310 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:11,310 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:12,009 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:12,009 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:13,735 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:14,678 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:17:14,698 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:14,698 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:17,296 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:17,297 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:18,771 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:19,920 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:19,920 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:22,579 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:22,580 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:23,808 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:25,231 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:25,231 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:25,986 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:17:26,305 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:26,337 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:26,337 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:27,883 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:27,883 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:28,813 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:30,612 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:30,612 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:31,445 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:32,890 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:32,890 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:33,486 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:33,831 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:35,507 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:35,574 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:35,590 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:37,525 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:38,278 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:38,279 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:39,053 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:39,553 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:40,927 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:40,927 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:41,309 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:41,344 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:41,344 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:41,603 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:43,596 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:43,601 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:43,657 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:44,073 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:45,713 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:46,289 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:46,305 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:47,757 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:48,955 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:48,955 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:49,244 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:49,830 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:51,719 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:17:51,880 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:53,953 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:54,358 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:54,474 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:17:56,023 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:56,055 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:17:56,316 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:56,348 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:56,351 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:57,029 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:57,029 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:58,092 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:17:59,515 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:59,697 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:59,697 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:00,138 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:02,208 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:02,459 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:02,473 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:04,276 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:04,779 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:05,076 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:05,076 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:06,325 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:07,382 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:07,785 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:07,786 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:09,401 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:10,028 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:10,549 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:11,344 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:11,373 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:11,374 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:11,493 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:13,203 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:13,203 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:13,759 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:15,205 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:15,815 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:15,920 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:15,920 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:17,875 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:18,635 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:18,639 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:19,985 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:20,424 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:21,362 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:22,025 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:23,958 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:23,958 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:24,079 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:25,515 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:26,022 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:18:26,099 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:26,342 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:26,375 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:26,375 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:26,660 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:26,661 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:28,145 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:29,335 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:29,339 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:30,177 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:30,707 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:32,088 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:32,093 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:32,317 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:34,355 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:34,877 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:35,728 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:36,385 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:37,432 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:37,435 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:38,450 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:40,126 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:40,126 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:40,490 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:40,848 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:41,352 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:41,395 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:41,395 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:42,536 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:42,777 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:42,777 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:43,592 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:45,489 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:45,489 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:45,672 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:45,884 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:47,740 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:48,203 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:48,206 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:49,805 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:50,866 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:50,866 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:50,932 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:51,876 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:53,553 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:53,586 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:53,925 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:55,993 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:56,025 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:18:56,025 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:56,233 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:56,233 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:56,367 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:56,400 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:56,400 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:58,060 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:18:58,973 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:00,112 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:01,167 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:01,643 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:01,644 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:02,168 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:04,243 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:04,274 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:04,274 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:06,301 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:06,301 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:06,957 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:06,957 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:08,354 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:09,672 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:09,672 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:10,421 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:11,398 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:11,402 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:11,409 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:11,409 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:12,342 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:12,342 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:12,493 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:14,578 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:15,165 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:16,520 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:16,603 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:17,717 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:17,717 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:18,642 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:20,377 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:20,377 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:20,691 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:21,706 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:22,766 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:23,055 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:23,055 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:24,830 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:25,771 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:25,772 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:26,043 DEBUG   SenderThread:1264 [sender.py:send():378] send: stats
2024-03-28 00:19:26,377 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:26,431 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:26,431 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:26,870 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:26,925 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:28,456 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:28,456 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:28,923 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:30,984 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:31,110 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:31,111 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:32,069 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:33,037 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:33,762 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:33,762 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:35,072 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:36,478 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:36,478 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:37,126 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:37,293 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:39,122 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:39,127 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:39,177 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:41,248 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:41,386 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:41,445 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:41,445 DEBUG   SenderThread:1264 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:41,784 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:41,784 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:43,269 INFO    Thread-16 :1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 00:19:44,482 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:44,482 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:46,501 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:19:47,219 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:47,219 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:49,876 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:49,876 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:51,621 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:19:52,614 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:52,621 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:55,389 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:55,975 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:19:56,388 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:57,913 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:57,913 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:58,204 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:19:59,959 INFO    SenderThread:1264 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\util\ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'")))
2024-03-28 00:20:00,610 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:00,610 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:01,764 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:02,422 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:20:03,333 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:03,333 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:06,016 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:06,048 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:06,810 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:08,683 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:08,683 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:11,374 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:11,374 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:11,406 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:13,010 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:20:14,028 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:14,028 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:16,711 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:16,711 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:16,886 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:19,364 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:19,366 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:21,962 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:22,045 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:22,045 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:24,700 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:24,700 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:26,459 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:27,448 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:29,993 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:20:30,056 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:30,056 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:32,083 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:32,777 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:32,777 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:35,559 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:37,145 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:38,114 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:38,129 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:40,831 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:40,835 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:41,447 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:43,450 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:43,457 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:46,118 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:46,118 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:46,717 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 00:20:47,248 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:48,746 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:48,746 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:49,802 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 00:20:51,364 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:51,364 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:53,999 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:53,999 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:54,833 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:56,641 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:56,641 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:59,285 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:59,285 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:59,866 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:01,940 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:01,940 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:03,671 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:21:04,582 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:04,593 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:04,897 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:07,210 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:07,210 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:09,850 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:09,850 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:09,928 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:12,505 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:12,505 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:14,958 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:15,179 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:15,179 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:17,785 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:17,785 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:19,980 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:20,420 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:20,420 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:23,048 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:23,048 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:25,014 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:25,691 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:25,691 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:28,332 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:28,332 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:30,046 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:30,972 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:30,972 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:33,612 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:33,612 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:35,077 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:36,252 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:36,252 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:38,892 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:38,892 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:40,102 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:41,533 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:41,533 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:44,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:44,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:45,132 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:46,813 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:46,813 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:49,438 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:49,438 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:50,161 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:51,466 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:21:54,153 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:54,153 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:55,239 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:56,729 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:56,729 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:59,370 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:59,370 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:00,329 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:02,010 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:02,010 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:04,654 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:04,654 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:05,361 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:07,293 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:07,293 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:09,929 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:09,929 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:10,386 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:12,570 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:12,570 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,211 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,211 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,416 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:17,851 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:17,851 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:20,446 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:20,493 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:20,493 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:21,690 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:22:23,134 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:23,134 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:25,472 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:25,770 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:25,770 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:28,409 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:28,409 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:30,501 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:31,051 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:31,051 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:33,706 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:22:33,722 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:33,722 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:35,529 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:36,328 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:36,328 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:38,950 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:38,950 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:40,547 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:41,600 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:41,600 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:44,244 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:44,244 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:45,580 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:46,884 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:46,884 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:49,523 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:49,523 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:50,607 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:52,163 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:52,163 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:54,818 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:54,818 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:55,635 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:57,460 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:57,460 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:00,093 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:00,093 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:00,659 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:02,731 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:02,731 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:05,377 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:05,377 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:05,698 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:08,008 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:08,008 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:10,651 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:10,651 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:10,745 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:13,337 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:23:13,337 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:13,337 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:15,774 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:15,947 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:15,947 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:18,589 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:18,589 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:20,826 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:21,234 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:21,234 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:23,876 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:23,876 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:25,888 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:26,512 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:26,512 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:29,154 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:29,154 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:30,932 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:31,800 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:31,809 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:34,449 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:34,449 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:35,971 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:37,087 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:37,087 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:39,743 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:39,743 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:41,019 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:42,386 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:42,386 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:45,024 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:45,024 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:46,045 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:47,668 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:47,669 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:50,306 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:50,306 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:51,075 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:52,961 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:23:52,977 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:52,977 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:55,570 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:55,570 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:56,104 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:58,239 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:58,239 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:00,909 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:00,913 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:01,129 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:03,564 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:03,564 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:06,155 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:06,234 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:06,234 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:08,889 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:08,889 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:11,184 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:11,560 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:11,560 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:14,213 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:14,213 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:16,209 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:16,900 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:16,900 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:19,557 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:19,557 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:21,237 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:22,241 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:22,241 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:24,894 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:24,894 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:26,262 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:27,565 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:27,565 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:30,218 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:30,234 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:31,286 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:31,521 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 00:24:32,917 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:24:32,933 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:32,933 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:35,568 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:35,568 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:36,307 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:38,222 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:38,222 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:40,877 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:40,877 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:41,333 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:43,546 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:43,546 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:46,205 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:46,205 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:46,358 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:48,887 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:48,887 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:51,386 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:51,544 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:51,544 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:54,196 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:54,196 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:56,412 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:56,867 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:56,867 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:59,534 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:59,534 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:01,459 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:02,196 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:02,196 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:04,878 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:04,879 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:06,577 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:07,532 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:07,532 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:10,202 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:10,202 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:11,647 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:12,871 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:25:12,886 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:12,886 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:15,511 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:15,511 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:16,672 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:18,179 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:18,179 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:20,845 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:20,845 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:21,694 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:23,500 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:23,500 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:26,167 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:26,167 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:26,717 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:28,822 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:28,822 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:31,488 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:31,488 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:31,740 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:34,169 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:34,169 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:36,756 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:36,835 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:36,835 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:39,487 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:39,487 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:41,779 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:42,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:42,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:44,833 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:44,833 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:46,802 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:47,509 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:47,509 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:50,177 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:50,177 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:51,828 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:52,865 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:25:52,865 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:52,865 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:55,487 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:55,487 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:56,854 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:58,159 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:58,159 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:00,838 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:00,838 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:01,876 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:03,514 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:03,515 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:06,159 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:06,159 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:06,897 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:08,811 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:08,811 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:11,478 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:11,478 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:11,918 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:14,130 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:14,130 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:16,801 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:16,801 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:16,941 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:19,465 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:19,481 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:21,962 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:22,134 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:22,134 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:24,792 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:24,792 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:26,988 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:27,444 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:27,444 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:30,097 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:30,112 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:32,024 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:32,794 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:26:32,810 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:32,810 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:35,435 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:35,435 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:37,111 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:38,087 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:38,087 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:40,757 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:40,757 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:42,169 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:43,425 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:43,425 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:46,094 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:46,094 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:47,238 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:48,776 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:48,776 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:51,429 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:51,429 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:52,292 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:54,082 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:54,082 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:56,751 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:56,751 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:57,394 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:59,437 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:59,437 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,104 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,105 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,449 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:04,772 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:04,772 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:07,426 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:07,426 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:07,536 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:10,094 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:10,094 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:12,638 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:12,764 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:27:12,780 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:12,780 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:15,415 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:15,415 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:17,694 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:18,080 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:18,080 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:20,725 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:20,725 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:22,718 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:23,379 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:23,379 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:26,063 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:26,063 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:27,742 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:28,716 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:28,716 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:31,385 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:31,385 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:32,765 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:34,067 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:34,067 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:36,718 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:36,718 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:37,785 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:39,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:39,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,072 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,072 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,810 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:44,758 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:44,758 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,398 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,398 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,838 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:50,079 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:50,079 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:52,748 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:27:52,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:52,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:52,858 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:55,389 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:55,404 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:57,883 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:58,072 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:58,072 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:00,725 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:00,725 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:02,908 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:03,392 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:03,392 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:06,046 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:06,046 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:07,929 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:08,729 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:08,729 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:11,380 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:11,380 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:12,950 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:14,034 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:14,050 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:16,701 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:16,701 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:17,969 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:19,382 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:19,382 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,034 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,034 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,993 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:24,689 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:24,689 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:27,386 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:27,386 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:28,015 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:30,040 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:30,040 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:32,749 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:28:32,765 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:32,765 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:33,032 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:35,372 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:35,372 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:38,025 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:38,025 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:38,056 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:40,710 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:40,710 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:43,081 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:43,379 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:43,379 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:46,052 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:46,052 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:48,104 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:48,703 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:48,703 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:51,353 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:51,353 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:53,142 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:54,022 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:54,022 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:56,692 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:56,692 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:58,152 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:59,381 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:59,381 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:02,052 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:02,052 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:03,177 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:29:04,479 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:04,479 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:05,701 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:44:06,658 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:06,658 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:08,701 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:29:56,183 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:29:57,177 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:29:59,486 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:29:59,486 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:01,307 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:01,543 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:01,543 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:04,183 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:04,183 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:04,918 WARNING FileStreamThread:1264 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C192E66CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001C192B8A040>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinmaysharmagsbf/CIFAR-10/k4ppw99v/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 14, 'content': ['2024-03-27T18:49:42.319135 521/782 [==================>...........] - ETA: 1:06 - loss: 1.4538 - accuracy: 0.4062\n']}}, 'dropped': 0}}
2024-03-28 09:30:06,346 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:06,817 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:06,817 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:09,469 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:09,469 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:11,373 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:12,078 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:12,078 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:14,719 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:14,719 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:16,401 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:17,345 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:17,345 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:19,969 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:19,979 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:21,427 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:22,608 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:22,608 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:25,249 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:25,249 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:26,458 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:27,871 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:27,871 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:30,503 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:30,503 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:31,490 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:33,125 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:33,125 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:35,814 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:35,814 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:36,521 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:38,374 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:38,374 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:41,023 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:41,023 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:41,547 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:43,634 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:43,634 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:46,260 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:46,260 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:46,574 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:48,897 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:48,897 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:51,523 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:51,523 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:51,601 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:54,151 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:54,151 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:56,629 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:56,771 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:56,771 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:59,406 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:59,406 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:01,653 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:02,062 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:02,062 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:04,717 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:04,717 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:06,680 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:07,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:07,387 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:10,041 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:10,041 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:11,707 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:12,696 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:12,696 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:15,367 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:31:15,382 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:15,382 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:16,734 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:18,007 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:18,007 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:20,657 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:20,657 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:21,757 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:23,310 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:23,310 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:25,963 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:25,963 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:26,782 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:28,632 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:28,632 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:31,304 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:31,305 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:31,806 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:33,975 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:33,975 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:36,633 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:36,633 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:36,838 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:39,290 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:39,290 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:41,864 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:41,960 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:41,960 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:44,626 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:44,626 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:46,889 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:47,317 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:47,317 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:49,939 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:49,939 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:51,921 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:52,596 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:52,596 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:55,252 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:31:55,252 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:55,252 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:56,949 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:57,844 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:57,844 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:00,486 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:00,486 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:01,983 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:03,131 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:03,131 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:05,771 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:05,771 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:07,007 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:08,405 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:08,405 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:11,061 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:11,061 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:12,069 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:13,687 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:13,687 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:16,328 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:16,328 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:17,193 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:18,967 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:18,967 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:21,607 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:21,607 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:22,250 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:24,247 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:24,247 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:26,871 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:26,871 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:27,280 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:29,510 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:29,510 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:32,150 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:32,150 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:32,308 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:34,821 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:32:34,821 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:34,821 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:37,335 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:37,429 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:37,429 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:40,068 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:40,068 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:42,363 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:42,709 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:42,709 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:45,346 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:45,346 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:47,392 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:47,987 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:47,987 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:50,625 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:50,625 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:52,418 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:53,264 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:53,264 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:55,900 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:55,900 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:57,440 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:58,537 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:58,537 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:01,209 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:01,210 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:02,468 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:03,846 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:03,846 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:06,533 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:06,533 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:07,492 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:09,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:09,172 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:11,797 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:11,797 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:12,520 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:14,470 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:33:14,490 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:14,490 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:17,083 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:17,090 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:17,575 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:19,740 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:19,740 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:22,394 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:22,394 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:22,614 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:25,032 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:25,032 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:27,655 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:27,686 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:27,686 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:30,338 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:30,338 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:32,684 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:32,982 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:32,982 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:35,630 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:35,630 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:37,720 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:38,269 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:38,269 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:40,927 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:40,928 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:42,751 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:43,569 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:43,569 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:46,216 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:46,216 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:47,791 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:48,859 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:48,859 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:51,497 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:51,497 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:52,816 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:54,166 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:33:54,166 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:54,166 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:56,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:56,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:57,845 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:59,399 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:59,399 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:02,038 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:02,038 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:02,872 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:04,665 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:04,665 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:07,308 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:07,308 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:07,900 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:09,954 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:09,954 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:12,596 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:12,596 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:12,926 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:15,221 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:15,221 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:17,861 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:17,861 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:17,955 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:20,502 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:20,502 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:23,031 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:23,131 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:23,131 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:25,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:25,764 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:28,122 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:28,405 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:28,405 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:31,051 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:31,051 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:33,187 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:33,720 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:34:33,720 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:33,720 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:36,327 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:36,327 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:38,214 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:38,973 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:38,973 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:41,624 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:41,624 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:43,247 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:44,268 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:44,268 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:46,931 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:46,932 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:48,273 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:49,571 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:49,571 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:52,217 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:52,217 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:53,318 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:54,848 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:54,848 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:57,521 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:57,521 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:58,340 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:35:00,174 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:00,174 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:02,828 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:02,828 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:03,368 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:35:05,471 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:05,471 ERROR   gpu       :1264 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:05,553 INFO    memory    :1264 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 09:35:05,553 DEBUG   SystemMonitor:1264 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:35:05,560 DEBUG   SystemMonitor:1264 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:35:05,572 ERROR   gpu       :1264 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:35:08,423 DEBUG   HandlerThread:1264 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:35:09,676 WARNING StreamThr :1264 [internal.py:is_dead():414] Internal process exiting, parent pid 20264 disappeared
2024-03-28 09:35:09,676 ERROR   StreamThr :1264 [internal.py:wandb_internal():152] Internal process shutdown.
2024-03-28 09:35:10,430 INFO    HandlerThread:1264 [handler.py:finish():869] shutting down handler
2024-03-28 09:35:10,430 INFO    HandlerThread:1264 [system_monitor.py:finish():203] Stopping system monitor
2024-03-28 09:35:10,430 INFO    HandlerThread:1264 [interfaces.py:finish():202] Joined cpu monitor
2024-03-28 09:35:10,446 INFO    HandlerThread:1264 [interfaces.py:finish():202] Joined disk monitor
2024-03-28 09:35:10,446 INFO    HandlerThread:1264 [interfaces.py:finish():202] Joined gpu monitor
2024-03-28 09:35:10,446 INFO    HandlerThread:1264 [interfaces.py:finish():202] Joined memory monitor
2024-03-28 09:35:10,446 INFO    HandlerThread:1264 [interfaces.py:finish():202] Joined network monitor
2024-03-28 09:35:10,613 INFO    WriterThread:1264 [datastore.py:close():296] close: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\run-k4ppw99v.wandb
2024-03-28 09:36:12,972 INFO    SenderThread:1264 [sender.py:finish():1521] shutting down sender
2024-03-28 09:36:15,323 INFO    SenderThread:1264 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-28 09:36:15,891 INFO    SenderThread:1264 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 09:36:15,895 INFO    SenderThread:1264 [dir_watcher.py:finish():388] scan: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files
2024-03-28 09:36:15,919 INFO    SenderThread:1264 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\conda-environment.yaml conda-environment.yaml
2024-03-28 09:36:15,966 INFO    SenderThread:1264 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\config.yaml config.yaml
2024-03-28 09:36:15,966 INFO    SenderThread:1264 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log output.log
2024-03-28 09:36:15,966 INFO    SenderThread:1264 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\requirements.txt requirements.txt
2024-03-28 09:36:15,966 INFO    SenderThread:1264 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\wandb-metadata.json wandb-metadata.json
2024-03-28 09:36:15,982 INFO    SenderThread:1264 [file_pusher.py:finish():172] shutting down file pusher
2024-03-28 09:36:15,982 INFO    SenderThread:1264 [file_pusher.py:join():178] waiting for file pusher
2024-03-28 09:36:17,550 INFO    wandb-upload_0:1264 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\conda-environment.yaml
2024-03-28 09:36:17,786 INFO    wandb-upload_2:1264 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\output.log
2024-03-28 09:36:17,786 INFO    wandb-upload_3:1264 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\requirements.txt
2024-03-28 09:36:17,801 INFO    wandb-upload_1:1264 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001553-k4ppw99v\files\config.yaml
2024-03-28 09:36:18,045 INFO    SenderThread:1264 [file_stream.py:finish():595] file stream finish called
2024-03-28 09:36:18,508 INFO    SenderThread:1264 [file_stream.py:finish():599] file stream finish is done
