2024-03-28 09:59:10,788 INFO    StreamThr :16800 [internal.py:wandb_internal():86] W&B internal server running at pid: 16800, started at: 2024-03-28 09:59:10.788453
2024-03-28 09:59:10,788 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:59:10,803 INFO    WriterThread:16800 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\run-9kw7n0xs.wandb
2024-03-28 09:59:10,803 DEBUG   SenderThread:16800 [sender.py:send():378] send: header
2024-03-28 09:59:10,808 DEBUG   SenderThread:16800 [sender.py:send():378] send: run
2024-03-28 09:59:11,793 INFO    SenderThread:16800 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files
2024-03-28 09:59:11,793 INFO    SenderThread:16800 [sender.py:_start_run_threads():1099] run started: 9kw7n0xs with start time 1711600150.788452
2024-03-28 09:59:11,803 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:59:11,803 DEBUG   SenderThread:16800 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:59:12,243 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:59:12,270 DEBUG   HandlerThread:16800 [system_info.py:__init__():26] System info init
2024-03-28 09:59:12,270 DEBUG   HandlerThread:16800 [system_info.py:__init__():41] System info init done
2024-03-28 09:59:12,270 INFO    HandlerThread:16800 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:59:12,271 INFO    SystemMonitor:16800 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:59:12,271 INFO    HandlerThread:16800 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:59:12,273 INFO    SystemMonitor:16800 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:59:12,273 INFO    SystemMonitor:16800 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:59:12,273 INFO    SystemMonitor:16800 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:59:12,273 INFO    SystemMonitor:16800 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:59:12,286 INFO    SystemMonitor:16800 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:59:12,293 DEBUG   HandlerThread:16800 [system_info.py:probe():150] Probing system
2024-03-28 09:59:12,293 DEBUG   HandlerThread:16800 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:59:12,293 DEBUG   HandlerThread:16800 [system_info.py:probe():198] Probing system done
2024-03-28 09:59:12,293 DEBUG   HandlerThread:16800 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:29:12.293226', 'startedAt': '2024-03-28T04:29:10.755113', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\client1.py', 'codePathLocal': 'client1.py', 'codePath': 'client1.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.25109100341797}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:59:12,293 INFO    HandlerThread:16800 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:59:12,293 INFO    HandlerThread:16800 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:59:12,293 DEBUG   HandlerThread:16800 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:59:12,303 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:12,800 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\conda-environment.yaml
2024-03-28 09:59:14,323 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:16,377 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:18,403 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:20,423 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:22,450 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:24,464 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:26,488 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:28,506 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:29,893 DEBUG   HandlerThread:16800 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:59:29,896 INFO    HandlerThread:16800 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:59:29,913 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:29,914 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:59:29,914 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:29,914 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:59:29,915 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:29,915 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:59:29,915 DEBUG   SenderThread:16800 [sender.py:send():378] send: files
2024-03-28 09:59:29,915 INFO    SenderThread:16800 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:59:29,975 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\conda-environment.yaml
2024-03-28 09:59:29,975 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\wandb-metadata.json
2024-03-28 09:59:30,524 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:30,773 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:59:30,773 DEBUG   SenderThread:16800 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:59:30,773 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:59:30,774 DEBUG   SenderThread:16800 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:59:30,776 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:59:30,979 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\requirements.txt
2024-03-28 09:59:31,194 DEBUG   SenderThread:16800 [sender.py:send():378] send: telemetry
2024-03-28 09:59:31,270 INFO    wandb-upload_0:16800 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpewjzf0icwandb\4unhmy7i-wandb-metadata.json
2024-03-28 09:59:32,043 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:32,543 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:32,999 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 09:59:34,563 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:35,017 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 09:59:36,584 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:37,270 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:38,608 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:40,635 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:42,312 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:42,737 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:43,097 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\config.yaml
2024-03-28 09:59:44,751 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:45,783 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:59:45,784 DEBUG   SenderThread:16800 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:59:45,787 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:59:46,785 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:48,273 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:48,798 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:50,821 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:52,844 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:53,318 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:54,901 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:56,260 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 09:59:56,968 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:59:58,290 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 09:59:58,319 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:59:59,020 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 10:00:00,315 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 10:00:00,790 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 10:00:00,791 DEBUG   SenderThread:16800 [sender.py:send_request():405] send_request: stop_status
2024-03-28 10:00:00,803 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 10:00:01,081 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 10:00:02,347 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 10:00:03,182 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 10:00:03,373 DEBUG   HandlerThread:16800 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 10:00:04,471 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 10:00:05,287 ERROR   gpu       :16800 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 10:00:06,511 INFO    Thread-16 :16800 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095910-9kw7n0xs\files\output.log
2024-03-28 10:00:06,557 INFO    memory    :16800 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 10:00:06,558 DEBUG   SystemMonitor:16800 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 10:00:06,559 DEBUG   SystemMonitor:16800 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 10:00:06,559 DEBUG   SystemMonitor:16800 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 10:00:06,565 DEBUG   SenderThread:16800 [sender.py:send():378] send: stats
2024-03-28 10:00:07,787 INFO    MainThread:16800 [internal.py:handle_exit():76] Internal process exited
